# These settings are synced to GitHub by https://github.com/apps/settings/. Install this app for your repo.

repository:
  has_wiki: false
  has_downloads: false
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

branches:
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: null
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      required_linear_history: true
      enforce_admins: null
      restrictions:
        apps: []
        users: []
        teams: []