# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  
  name: repo-name

  description: description of repo

  homepage: https://example.github.io/

  topics: github, probot

  private: false

  has_issues: true

  has_projects: true

  has_wiki: true

  has_downloads: true

  default_branch: master

  allow_squash_merge: true

  allow_merge_commit: true

  allow_rebase_merge: true

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []