name: Biotope Quality Gate

on: pull_request

jobs:
  run-linters:
    name: Biotope Quality Gate
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository and setup Node.js
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          prettier: true
          stylelint: true

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2