name: Qualitygate
on: [pull_request]

jobs:
  qualitygate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run lint:code | reviewdog -reporter=github-pr-check
          npm run lint:styles | reviewdog -reporter=github-pr-check
      

      - uses: wagoid/commitlint-github-action@v2
        with:
            configFile: .commitlintrc.json
            firstParent: true
            failOnWarnings: false