name: Qualitygate
on: [pull_request]

jobs:
  qualitygate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install

      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
      - name: alex
        uses: reviewdog/action-alex@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          level: warning
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review


      - uses: wagoid/commitlint-github-action@v2
        with:
            configFile: .commitlintrc.json
            firstParent: true
            failOnWarnings: false

